# cloudbuild-hotfix.yaml - Quick deployment for API fixes
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/runaway-coach:$BUILD_ID', '.']
    timeout: '600s'
  
  # Push to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/runaway-coach:$BUILD_ID']
    timeout: '300s'
  
  # Deploy to Cloud Run (keeping existing env vars)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'runaway-coach-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/runaway-coach:$BUILD_ID'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

images:
  - 'gcr.io/$PROJECT_ID/runaway-coach:$BUILD_ID'