# cloudbuild.yaml - Optimized for Cloud Run
steps:
  # Build the Docker image with more resources
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/runaway-coach:$BUILD_ID', '.']
    timeout: '600s'
  
  # Push to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/runaway-coach:$BUILD_ID']
    timeout: '300s'
  
  # Deploy to Cloud Run with optimized settings
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'runaway-coach-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/runaway-coach:$BUILD_ID'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8000'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--timeout'
    - '600'
    - '--max-instances'
    - '10'
    - '--min-instances'
    - '0'
    - '--concurrency'
    - '80'
    - '--set-env-vars'
    - 'ENVIRONMENT=production,PYTHONUNBUFFERED=1,PYTHONPATH=/app,CLAUDE_MODEL=claude-3-5-sonnet-20241022,SUPABASE_URL=https://nkxvjcdxiyjbndjvfmqy.supabase.co,REDIS_URL=redis://localhost:6379/0,API_HOST=0.0.0.0,API_PORT=8000,API_ALGORITHM=HS256,LOG_LEVEL=INFO,LOG_FORMAT=json,SWIFT_APP_BASE_URL=http://localhost:3000'
    - '--cpu-throttling'
    - '--no-cpu-throttling'
    - '--set-secrets'
    - 'ANTHROPIC_API_KEY=runaway-anthropic-key:latest,SUPABASE_SERVICE_KEY=runaway-supabase-service:latest,SUPABASE_ANON_KEY=runaway-supabase-anon:latest,SUPABASE_JWT_SECRET=runaway-supabase-jwt-secret:latest,API_SECRET_KEY=runaway-api-secret:latest,SWIFT_APP_API_KEY=runaway-swift-api-key:latest'

options:
  # Use more powerful machine for builds
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

images:
  - 'gcr.io/$PROJECT_ID/runaway-coach:$BUILD_ID'